"""Authentication utilities for account passwords and cloud-issued API keys.

Passwords are bcrypt-hashed. API keys are generated by the gateway, shown only at
creation time, and stored as SHA-256 hashes. Authenticated endpoints require the
X-API-Key header.
"""

import hashlib
import secrets
from datetime import datetime
from typing import Optional

import bcrypt
from fastapi import Depends, HTTPException, Request, Security
from fastapi.security import APIKeyHeader
from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from .database import get_db

api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)

PASSWORD_MIN_LENGTH = 12
PASSWORD_MAX_LENGTH = 72


def validate_password(password: str) -> str:
    """Validate a password without silently truncating user input."""
    if len(password) < PASSWORD_MIN_LENGTH:
        raise ValueError(f"Password must be at least {PASSWORD_MIN_LENGTH} characters")
    if len(password.encode("utf-8")) > PASSWORD_MAX_LENGTH:
        raise ValueError("Password is too long for bcrypt; use at most 72 UTF-8 bytes")
    return password


def hash_password(password: str) -> str:
    return bcrypt.hashpw(validate_password(password).encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def verify_password(plain: str, hashed: str) -> bool:
    try:
        validate_password(plain)
    except ValueError:
        return False
    return bcrypt.checkpw(plain.encode("utf-8"), hashed.encode("utf-8"))


def generate_api_key() -> str:
    return f"pk_{secrets.token_urlsafe(32)}"


def hash_api_key(key: str) -> str:
    return hashlib.sha256(key.encode("utf-8")).hexdigest()


async def get_current_user(
    request: Request,
    api_key: Optional[str] = Security(api_key_header),
    db: AsyncSession = Depends(get_db),
):
    """Resolve the authenticated user from an active cloud-issued API key."""
    from .models import APIKey, User

    if not api_key:
        raise HTTPException(status_code=401, detail="Missing X-API-Key header")

    now = datetime.utcnow()
    key_hash = hash_api_key(api_key)
    result = await db.execute(
        select(APIKey).where(
            APIKey.key_hash == key_hash,
            APIKey.revoked_at.is_(None),
            or_(APIKey.expires_at.is_(None), APIKey.expires_at > now),
        )
    )
    key_record = result.scalar_one_or_none()
    if key_record:
        user_result = await db.execute(select(User).where(User.id == key_record.user_id))
        user = user_result.scalar_one_or_none()
        if user and user.is_active:
            key_record.last_used_at = now
            request.state.user_id = str(user.id)
            return user

    # Compatibility for deployments upgraded before the api_keys table existed.
    result = await db.execute(select(User).where(User.api_key_hash == key_hash))
    user = result.scalar_one_or_none()
    if not user or not user.is_active:
        raise HTTPException(status_code=401, detail="Invalid or expired API key")
    request.state.user_id = str(user.id)
    return user


class RateLimiter:
    def __init__(self, max_requests: int = 60, window_seconds: int = 60):
        self.max_requests = max_requests
        self.window = window_seconds
        self._requests: dict[str, list[float]] = {}

    def check(self, key: str) -> bool:
        import time
        now = time.time()
        self._requests.setdefault(key, [])
        self._requests[key] = [t for t in self._requests[key] if now - t < self.window]
        if len(self._requests[key]) >= self.max_requests:
            return False
        self._requests[key].append(now)
        return True


rate_limiter = RateLimiter()
